// <auto-generated />
using System;
using Khunghinh.Api.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Khunghinh.Api.Migrations
{
    [DbContext(typeof(KhunghinhContext))]
    [Migration("20251019122900_Baseline_20251019")]
    partial class Baseline_20251019
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.BaoCaoViPham", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("KhungHinhId")
                        .HasColumnType("bigint");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MoTaThem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<long?>("NguoiBaoCaoId")
                        .HasColumnType("bigint");

                    b.Property<string>("TrangThaiXuLy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("cho_duyet");

                    b.HasKey("Id")
                        .HasName("PK__BaoCaoVi__3214EC07D41AC354");

                    b.HasIndex("KhungHinhId");

                    b.HasIndex("NguoiBaoCaoId");

                    b.HasIndex(new[] { "TrangThaiXuLy" }, "IX_BCVP_TrangThai");

                    b.ToTable("BaoCaoViPham", (string)null);
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.CaiDatHeThong", b =>
                {
                    b.Property<string>("Khoa")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GiaTri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("Khoa")
                        .HasName("PK__CaiDatHe__77B4176EDB10F59C");

                    b.ToTable("CaiDatHeThong", (string)null);
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.DangNhapNgoai", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EmailXacThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LanCuoiDangNhap")
                        .HasColumnType("datetime2");

                    b.Property<long>("NguoiDungId")
                        .HasColumnType("bigint");

                    b.Property<string>("NhaCungCap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RefreshTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__DangNhap__3214EC07D6EA7822");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex(new[] { "NhaCungCap", "ProviderUserId" }, "UQ_DNN")
                        .IsUnique();

                    b.ToTable("DangNhapNgoai", (string)null);
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.KhungBienThe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnhPngUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("KhungHinhId")
                        .HasColumnType("bigint");

                    b.Property<string>("TenBienThe")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("hoat_dong");

                    b.HasKey("Id")
                        .HasName("PK__KhungBie__3214EC074C69A756");

                    b.HasIndex(new[] { "KhungHinhId", "TrangThai", "ThuTu" }, "IX_KBT_Khung");

                    b.ToTable("KhungBienThe", (string)null);
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.KhungHinh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CheDoHienThi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("ChuSoHuuId")
                        .HasColumnType("bigint");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("LuotTai")
                        .HasColumnType("bigint");

                    b.Property<long>("LuotXem")
                        .HasColumnType("bigint");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("NgayChinhSua")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("QrImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UrlXemTruoc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__KhungHin__3214EC07DCDC23BC");

                    b.HasIndex("ChuSoHuuId");

                    b.HasIndex(new[] { "NgayDang" }, "IX_KH_NgayDang");

                    b.HasIndex(new[] { "Alias" }, "UQ_KH_Alias")
                        .IsUnique();

                    b.ToTable("KhungHinh", (string)null);
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.NguoiDung", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnhDaiDienUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__NguoiDun__3214EC07AB0D67F6");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D10534D892FBAB")
                        .IsUnique();

                    b.ToTable("NguoiDung", null, t =>
                        {
                            t.HasTrigger("trg_NguoiDung_Delete");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.SuKienKhung", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("HeDieuHanh")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("IpHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<long>("KhungHinhId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiSuKien")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<long?>("NguoiDungId")
                        .HasColumnType("bigint");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<string>("ThanhPho")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ThietBi")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("ThoiDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TrinhDuyet")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id")
                        .HasName("PK__SuKienKh__3214EC0736C55AD3");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex(new[] { "KhungHinhId", "ThoiDiem" }, "IX_SK_Khung_ThoiDiem");

                    b.HasIndex(new[] { "LoaiSuKien" }, "IX_SK_Loai");

                    b.ToTable("SuKienKhung", null, t =>
                        {
                            t.HasTrigger("trg_SuKienKhung_AfterInsert");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.ThongKeNgay", b =>
                {
                    b.Property<DateOnly>("Ngay")
                        .HasColumnType("date");

                    b.Property<long>("KhungHinhId")
                        .HasColumnType("bigint");

                    b.Property<int>("DoiKhung")
                        .HasColumnType("int");

                    b.Property<int>("QuetQr")
                        .HasColumnType("int");

                    b.Property<int>("Tai")
                        .HasColumnType("int");

                    b.Property<int>("Xem")
                        .HasColumnType("int");

                    b.HasKey("Ngay", "KhungHinhId")
                        .HasName("PK_TK");

                    b.HasIndex("KhungHinhId");

                    b.ToTable("ThongKeNgay", (string)null);
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.BaoCaoViPham", b =>
                {
                    b.HasOne("Khunghinh.Api.Data.Entities.KhungHinh", "KhungHinh")
                        .WithMany("BaoCaoViPhams")
                        .HasForeignKey("KhungHinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BCVP_KH");

                    b.HasOne("Khunghinh.Api.Data.Entities.NguoiDung", "NguoiBaoCao")
                        .WithMany("BaoCaoViPhams")
                        .HasForeignKey("NguoiBaoCaoId")
                        .HasConstraintName("FK_BCVP_NBC");

                    b.Navigation("KhungHinh");

                    b.Navigation("NguoiBaoCao");
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.DangNhapNgoai", b =>
                {
                    b.HasOne("Khunghinh.Api.Data.Entities.NguoiDung", "NguoiDung")
                        .WithMany("DangNhapNgoais")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DNN_ND");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.KhungBienThe", b =>
                {
                    b.HasOne("Khunghinh.Api.Data.Entities.KhungHinh", "KhungHinh")
                        .WithMany("KhungBienThes")
                        .HasForeignKey("KhungHinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KBT_KH");

                    b.Navigation("KhungHinh");
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.KhungHinh", b =>
                {
                    b.HasOne("Khunghinh.Api.Data.Entities.NguoiDung", "ChuSoHuu")
                        .WithMany("KhungHinhs")
                        .HasForeignKey("ChuSoHuuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_KH_ND");

                    b.Navigation("ChuSoHuu");
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.SuKienKhung", b =>
                {
                    b.HasOne("Khunghinh.Api.Data.Entities.KhungHinh", "KhungHinh")
                        .WithMany("SuKienKhungs")
                        .HasForeignKey("KhungHinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SK_KH");

                    b.HasOne("Khunghinh.Api.Data.Entities.NguoiDung", "NguoiDung")
                        .WithMany("SuKienKhungs")
                        .HasForeignKey("NguoiDungId")
                        .HasConstraintName("FK_SK_ND");

                    b.Navigation("KhungHinh");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.ThongKeNgay", b =>
                {
                    b.HasOne("Khunghinh.Api.Data.Entities.KhungHinh", "KhungHinh")
                        .WithMany("ThongKeNgays")
                        .HasForeignKey("KhungHinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TK_KH");

                    b.Navigation("KhungHinh");
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.KhungHinh", b =>
                {
                    b.Navigation("BaoCaoViPhams");

                    b.Navigation("KhungBienThes");

                    b.Navigation("SuKienKhungs");

                    b.Navigation("ThongKeNgays");
                });

            modelBuilder.Entity("Khunghinh.Api.Data.Entities.NguoiDung", b =>
                {
                    b.Navigation("BaoCaoViPhams");

                    b.Navigation("DangNhapNgoais");

                    b.Navigation("KhungHinhs");

                    b.Navigation("SuKienKhungs");
                });
#pragma warning restore 612, 618
        }
    }
}
